Job.all.destroy_all
Area.all.destroy_all
User.all.destroy_all
# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ area_name: 'Chicago' }, { area_name: 'Copenhagen' }])

# area_names = Area.create([{ area_name: '北海道'}, { area_name: '東京'}, { area_name: '神奈川'}])
User.create(name: '野崎優子', kana: 'ノザキユウコ', sex: '女', age: 22, email: 'nozaki@rejob.co.jp', password: 'a0000')
User.create(name: '池上里実', kana: 'イケガミサトミ', sex: '女', age: 22, email: 'ikegami@rejob.co.jp', password: 'b0000')
User.create(name: '荻野夏帆', kana: 'オギノカホ', sex: '女', age: 22, email: 'ogino@rejob.co.jp', password: 'c0000')
User.create(name: '黒田蓮', kana: 'クロダレン', sex: '男', age: 23, email: 'kuroda@rejob.co.jp', password: 'd0000')
User.create(name: '荒巻遵', kana: 'アラマキジュン', sex: '男', age: 23, email: 'aramaki@rejob.co.jp', password: 'e0000')


Job.create(title: '働くママさんも安心！', description: '周りには病院施設、調剤薬局などの施設が多数あり、女性のお客様の来店が非常に多いお店ですので女性の施術スタッフの方は働きやすい環境。', area: '東京都')
Job.create(title: '★新規Open★', description: '社内独立制度有り！ 将来独立開業したい方、FCにご興味のある方お待ちしております。', area: '福島県')
Job.create(title: '和やかな雰囲気の職場です★', description: '都会の喧騒を忘れ、リラックスリゾートで、お客様にあなたのすばらしい癒しを提供しませんか。', area: '神奈川県')
Job.create(title: '経験者優遇します', description: '「ありがとう」と言える心を大切にし、 皆様から「ありがとう」と言われる企業として成長し続けます。', area: '埼玉県')
Job.create(title: '社保完備！', description: '★完全週休2日制で仕事もプライベートも充実♪ ', area: '兵庫県')
Job.create(title: '新規オープン', description: '一緒に会社を作りあげていきたい方　大募集', area: '北海道')
Job.create(title: '駅チカ！！！', description: '私たちと一緒に桜の木の下で働きませんか', area: '埼玉県')
Job.create(title: '都会の中心部にあります！', description: '東京の都心で働ける、駅近だよー', area: '東京都')
Job.create(title: '経験がなくても大歓迎', description: '最寄りは横浜！未経験者集まれー。', area: '神奈川県')
Job.create(title: '店員さんがみんな面白い。研修も充実', description: '先輩社員が優しく指導。スタッフが楽しいから長く続けられる。', area: '大阪府')
Job.create(title: '★未経験も充実した研修で安心。一緒に働きましょう♪', description: '今までの経験を活かしたい方も未経験者の方でも、是非ご応募お待ちしております☆ *充実の研修制度* 転職される方や、ブランクがある方でもご安心ください! ', area: '愛知県')
Job.create(title: 'アットホームを大切に、未経験の方も大歓迎！正社員もパートも働き方いろいろいろ♪', description: 'お客様の笑顔をもっと作りたい。 その為にはスタッフが笑顔でイキイキと働ける環境が大事だと考え、待遇の充実・職場環境の向上に取り組んでいます。 無理のない生活ペースで、プライベートも楽しるめように週休2日(土日も可)やリフレッシュ休暇など休みを充実させました。', area: '三重県')
Job.create(title: '未経験の方もOK!接客も技術もプロのセラピストに!', description: 'アットホームな当店ではご家族、カップルでのご利用も多く、癒しを求める方々にたくさんの支持をいただいております。 ', area: '岐阜県')
Job.create(title: 'スタッフ達にものすごく大人気の☆自由シフト制☆(^^♪', description: 'オープンしてもうすぐ1年のお店ですが、スタッフ同士がとっても仲良しなので、日々楽しく働けますよ。(^^♪ 現在、技術に伸び悩んでいる方や、技術を活かしきれていない方など、向上心のある方は特に大歓迎です。!(^^)! ご応募お待ちしております。', area: '長野県')
Job.create(title: '“個”よりも“チーム”を大事に考えられる方、お待ちしています☆', description: '風通しの良い人間関係が自慢です！', area: '石川県')
Job.create(title: 'やる気・元気のある方大歓迎!オリンピック選手も公認のサロン!', description: 'マストレッチを通してお客様が健康になる為のお手伝いをします。', area: '大阪府')
Job.create(title: '★研修充実★ほぐし〜カイロプラクティック矯正も学べます★', description: 'besthandsグループ 世田谷区を拠点に5院', area: '和歌山県')
Job.create(title: 'テルマー湯内、スタッフ大募集!', description: '新設される高級SPA内に併設されるアロマ・エステサロンのオープニングスタッフの募集です!', area: '三重県')
Job.create(title: '未経験の方もOK☆接客も技術もプロのセラピストに!', description: 'アットホームな当店ではご家族、カップルでのご利用も多く、 癒しを求める方々にたくさんの支持をいただいております。 ', area: '奈良県')
Job.create(title: '向上心のある方、やる気のある方なら未経験でも大歓迎です。', description: '愛心グループでは、未来の経営者、幹部候補生をお待ちしています。', area: '滋賀県')


Area.create(area_name: '東京都')
Area.create(area_name: '神奈川県')
Area.create(area_name: '千葉県')
Area.create(area_name: '埼玉県')
Area.create(area_name: '愛知県')
Area.create(area_name: '大阪府')
Area.create(area_name: '北海道')
Area.create(area_name: '青森県')
Area.create(area_name: '岩手県')
Area.create(area_name: '宮城県')
Area.create(area_name: '秋田県')
Area.create(area_name: '山形県')
Area.create(area_name: '福島県')
Area.create(area_name: '茨城県')
Area.create(area_name: '栃木県')
Area.create(area_name: '群馬県')
Area.create(area_name: '新潟県')
Area.create(area_name: '富山県')
Area.create(area_name: '石川県')
Area.create(area_name: '福井県')
Area.create(area_name: '山梨県')
Area.create(area_name: '長野県')
Area.create(area_name: '岐阜県')
Area.create(area_name: '静岡県')
Area.create(area_name: '三重県')
Area.create(area_name: '滋賀県')
Area.create(area_name: '京都府')
Area.create(area_name: '兵庫県')
Area.create(area_name: '奈良県')
Area.create(area_name: '和歌山県')
Area.create(area_name: '鳥取県')
Area.create(area_name: '島根県')
Area.create(area_name: '岡山県')
Area.create(area_name: '広島県')
Area.create(area_name: '山口県')
Area.create(area_name: '徳島県')
Area.create(area_name: '香川県')
Area.create(area_name: '愛媛県')
Area.create(area_name: '高知県')
Area.create(area_name: '福岡県')
Area.create(area_name: '佐賀県')
Area.create(area_name: '長崎県')
Area.create(area_name: '熊本県')
Area.create(area_name: '大分県')
Area.create(area_name: '宮崎県')
Area.create(area_name: '鹿児島県')
Area.create(area_name: '沖縄県')

puts 'やったね！'
